import { Question, LeaderboardPlayer, CharacterType } from './types';

type QuestionsByStage = { [stage: number]: Question[] };
type AllQuestions = { [key in 'Easy' | 'Normal' | 'Hard']: QuestionsByStage };

export const QUESTIONS: AllQuestions = {
  Easy: {
    1: [
      { question: "What does 'recycling' mean?", options: ["Throwing things away", "Turning waste into new items", "Burning trash", "Burying garbage"], correctAnswer: "Turning waste into new items", fact: "Recycling conserves natural resources, saves energy, and reduces pollution." },
      { question: "What should you do with lights when you leave a room?", options: ["Leave them on", "Turn them off", "Flicker them", "Unscrew the bulb"], correctAnswer: "Turn them off", fact: "Turning off lights saves electricity, which is often generated by burning fossil fuels." },
      { question: "Which of these is a source of clean energy?", options: ["Coal", "Gasoline", "Wind", "Diesel"], correctAnswer: "Wind", fact: "Wind turbines convert the kinetic energy in the wind into clean electricity." }
    ],
    2: [
      { question: "What is the main ingredient in glass?", options: ["Plastic", "Wood", "Sand", "Metal"], correctAnswer: "Sand", fact: "Glass is infinitely recyclable without any loss in quality or purity." },
      { question: "What gas do plants release that we need to breathe?", options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Methane"], correctAnswer: "Oxygen", fact: "Photosynthesis in plants and trees produces the oxygen essential for most life on Earth." },
      { question: "Why is it important to not waste water?", options: ["It costs money", "It makes puddles", "There is a limited amount of fresh water", "It's noisy"], correctAnswer: "There is a limited amount of fresh water", fact: "Less than 1% of the world's water is fresh and accessible for us to use." }
    ],
    3: [
      { question: "What is a 'compost' pile?", options: ["A pile of rocks", "A pile of old toys", "A pile of recycled food and yard waste", "A pile of clothes"], correctAnswer: "A pile of recycled food and yard waste", fact: "Compost enriches soil, helping retain moisture and suppress plant diseases and pests." },
      { question: "Which of these animals is a famous symbol of endangered species?", options: ["Chicken", "Giant Panda", "Cow", "Pigeon"], correctAnswer: "Giant Panda", fact: "Giant Pandas are native to China and are a symbol of conservation efforts worldwide." },
      { question: "What is deforestation?", options: ["Planting new trees", "Watering trees", "Cutting down forests", "Climbing trees"], correctAnswer: "Cutting down forests", fact: "Forests are home to 80% of the world's terrestrial biodiversity." }
    ],
    4: [
      { question: "What kind of bag is best to reuse for shopping?", options: ["Plastic bag", "Paper bag", "Cloth bag", "A new bag every time"], correctAnswer: "Cloth bag", fact: "A single reusable bag can replace hundreds of plastic bags over its lifetime." },
      { question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctAnswer: "Pacific", fact: "The Pacific Ocean is so large that it could hold all of the continents." },
      { question: "What is littering?", options: ["Reading a book", "Dropping trash on the ground", "Planting a flower", "Recycling"], correctAnswer: "Dropping trash on the ground", fact: "Litter can harm wildlife, contaminate water sources, and is unsightly." }
    ],
    5: [
      { question: "Which of the 3 R's is the most important for helping the environment?", options: ["Recycle", "Reuse", "Reduce", "They are all equal"], correctAnswer: "Reduce", fact: "Reducing the amount of stuff you use in the first place is the most effective way to lessen your impact." },
      { question: "What is a natural habitat?", options: ["A house for people", "A zoo cage", "The natural home of a plant or animal", "A playground"], correctAnswer: "The natural home of a plant or animal", fact: "Protecting natural habitats is crucial for preventing species from becoming endangered." },
      { question: "Why are bees important for the environment?", options: ["They make honey", "They pollinate plants", "They are yellow and black", "They can sting"], correctAnswer: "They pollinate plants", fact: "About one-third of the food we eat relies on pollination by bees and other insects." }
    ],
    6: [
      { question: "What material are most drink cans made from?", options: ["Steel", "Copper", "Aluminum", "Plastic"], correctAnswer: "Aluminum", fact: "Recycling one aluminum can saves enough energy to run a TV for three hours." },
      { question: "What is the name for the process of water falling from the clouds?", options: ["Evaporation", "Condensation", "Precipitation", "Collection"], correctAnswer: "Precipitation", fact: "Precipitation can be rain, sleet, hail, or snow." },
      { question: "What causes air pollution?", options: ["Singing birds", "Flowing rivers", "Smoke from cars and factories", "Growing trees"], correctAnswer: "Smoke from cars and factories", fact: "Air pollution can cause respiratory problems and other health issues." }
    ],
    7: [
      { question: "What is a 'food chain'?", options: ["A type of restaurant", "A list of groceries", "How energy is passed from one living thing to another", "A kind of necklace"], correctAnswer: "How energy is passed from one living thing to another", fact: "The sun is the original source of energy for almost all food chains on Earth." },
      { question: "Which of these should NOT go in a recycling bin?", options: ["Plastic bottles", "Food waste", "Newspapers", "Glass jars"], correctAnswer: "Food waste", fact: "Food waste can contaminate other recyclables, making them unusable." },
      { question: "What is the protective layer in the atmosphere that blocks harmful UV rays?", options: ["The Cloud Layer", "The Fog Layer", "The Ozone Layer", "The Smog Layer"], correctAnswer: "The Ozone Layer", fact: "The ozone layer acts like a giant sunscreen for the Earth." }
    ],
    8: [
      { question: "What does 'biodegradable' mean?", options: ["Something artificial", "Something that can be broken down naturally by bacteria", "Something that is very strong", "Something that is brightly colored"], correctAnswer: "Something that can be broken down naturally by bacteria", fact: "Materials like paper and food scraps are biodegradable, while most plastics are not." },
      { question: "What is a coral reef?", options: ["A type of mountain", "An underwater ecosystem built by tiny animals", "A desert oasis", "A forest of seaweed"], correctAnswer: "An underwater ecosystem built by tiny animals", fact: "Often called 'rainforests of the sea,' coral reefs support a quarter of all marine species." },
      { question: "Which of these is a fossil fuel?", options: ["Wood", "Solar Power", "Coal", "Wind"], correctAnswer: "Coal", fact: "Fossil fuels were formed from the remains of ancient plants and animals over millions of years." }
    ],
  },
  Normal: {
    1: [
      { question: "What is the Great Pacific Garbage Patch?", options: ["An island resort", "A marine national park", "A large area of floating plastic trash in the ocean", "A famous coral reef"], correctAnswer: "A large area of floating plastic trash in the ocean", fact: "It's the largest accumulation of ocean plastic in the world, estimated to be twice the size of Texas." },
      { question: "What does 'carbon footprint' refer to?", options: ["The size of your shoe", "A type of fossil", "The total amount of greenhouse gases produced by a person or entity", "The mark a tire leaves"], correctAnswer: "The total amount of greenhouse gases produced by a person or entity", fact: "Common ways to reduce your carbon footprint include driving less, using less energy, and eating less meat." },
      { question: "What is an invasive species?", options: ["A species native to an ecosystem", "An animal that is very shy", "A non-native species that harms the local environment", "A species that lives in space"], correctAnswer: "A non-native species that harms the local environment", fact: "Invasive species can outcompete native wildlife for resources, leading to a decline in biodiversity." }
    ],
    2: [
      { question: "What is acid rain?", options: ["Rain that tastes sour", "Rainfall made acidic by atmospheric pollution", "A type of soda", "Rain that cleans statues"], correctAnswer: "Rainfall made acidic by atmospheric pollution", fact: "Acid rain is caused by emissions of sulfur dioxide and nitrogen oxide, which react with water molecules in the atmosphere." },
      { question: "Which of these is NOT a major greenhouse gas?", options: ["Carbon Dioxide (CO2)", "Methane (CH4)", "Oxygen (O2)", "Nitrous Oxide (N2O)"], correctAnswer: "Oxygen (O2)", fact: "Greenhouse gases trap heat in the atmosphere, leading to global warming." },
      { question: "What is 'light pollution'?", options: ["A power outage", "Bright, decorative lights", "Excessive artificial light that harms ecosystems and our view of the stars", "A solar flare"], correctAnswer: "Excessive artificial light that harms ecosystems and our view of the stars", fact: "Light pollution can disrupt the migratory patterns of birds and the life cycles of nocturnal animals." }
    ],
    3: [
      { question: "What is the primary function of wetlands?", options: ["They are good for building on", "They act as natural water filters and flood control", "They are sources of pollution", "They have no real purpose"], correctAnswer: "They act as natural water filters and flood control", fact: "Wetlands are among the most productive ecosystems in the world, comparable to rain forests and coral reefs." },
      { question: "What does 'potable' water mean?", options: ["Water used for plants", "Salt water", "Water that is safe to drink", "Water in a pot"], correctAnswer: "Water that is safe to drink", fact: "Globally, over 2 billion people lack access to safely managed drinking water services." },
      { question: "What is geothermal energy?", options: ["Energy from burning wood", "Heat energy from within the Earth", "Energy from the tides", "Energy from gasoline"], correctAnswer: "Heat energy from within the Earth", fact: "Geothermal power plants use steam produced from reservoirs of hot water found a few miles below the Earth's surface." }
    ],
    4: [
      { question: "What is 'sustainable' agriculture?", options: ["Farming that uses lots of chemicals", "Farming that can be continued indefinitely without harming the environment", "Farming only one type of crop", "Farming with robots"], correctAnswer: "Farming that can be continued indefinitely without harming the environment", fact: "Techniques include crop rotation, reducing tillage, and using natural pest controls." },
      { question: "Which layer of the Earth's atmosphere do we live in?", options: ["Stratosphere", "Mesosphere", "Thermosphere", "Troposphere"], correctAnswer: "Troposphere", fact: "The troposphere contains about 75% of the atmosphere's mass and 99% of its water vapor." },
      { question: "What is a 'carbon sink'?", options: ["A type of kitchen appliance", "A place where carbon is stored", "A source of carbon emissions", "A carbon-based life form"], correctAnswer: "A place where carbon is stored", fact: "The main natural carbon sinks are plants, the ocean, and soil." }
    ],
    5: [
      { question: "What is biodiversity?", options: ["The study of biographies", "The variety of life in a particular habitat or ecosystem", "A lack of living things", "A type of fuel"], correctAnswer: "The variety of life in a particular habitat or ecosystem", fact: "High biodiversity helps ensure an ecosystem's resilience to disturbances like climate change or disease." },
      { question: "What are 'microplastics'?", options: ["Very small toys", "Tiny plastic particles that pollute the environment", "A type of fabric", "Microscopic organisms"], correctAnswer: "Tiny plastic particles that pollute the environment", fact: "Microplastics have been found everywhere from the deepest oceans to the highest mountains, and even in our food and water." },
      { question: "What does the term 'organic' mean in farming?", options: ["It was grown on another planet", "It was grown without the use of synthetic pesticides and fertilizers", "It was grown indoors", "It is a specific brand"], correctAnswer: "It was grown without the use of synthetic pesticides and fertilizers", fact: "Organic farming practices are designed to promote ecological balance and conserve biodiversity." }
    ],
    6: [
      { question: "What is soil erosion?", options: ["The process of creating new soil", "The wearing away of topsoil by wind and water", "The mixing of different soils", "The study of soil"], correctAnswer: "The wearing away of topsoil by wind and water", fact: "Healthy vegetation cover is one of the best ways to prevent soil erosion." },
      { question: "What is the main environmental concern with using nuclear power?", options: ["Air pollution", "Greenhouse gas emissions", "Disposal of radioactive waste", "Noise pollution"], correctAnswer: "Disposal of radioactive waste", fact: "Nuclear power plants themselves produce no greenhouse gas emissions during operation." },
      { question: "What is the 'greenhouse effect'?", options: ["The way plants grow in a greenhouse", "When gases in the atmosphere trap the sun's heat", "Painting your house green", "A special effect in movies"], correctAnswer: "When gases in the atmosphere trap the sun's heat", fact: "The greenhouse effect is natural and necessary for life on Earth, but human activities have intensified it, causing global warming." }
    ],
    7: [
      { question: "What is 'aquaculture'?", options: ["A water-based theme park", "The farming of fish, crustaceans, mollusks, and aquatic plants", "The scientific study of water", "A type of water sport"], correctAnswer: "The farming of fish, crustaceans, mollusks, and aquatic plants", fact: "Aquaculture is the fastest-growing food production sector and now accounts for half of the fish consumed globally." },
      { question: "Which of these is a major component of smog?", options: ["Water vapor", "Ground-level ozone", "Pure oxygen", "Nitrogen"], correctAnswer: "Ground-level ozone", fact: "Unlike the protective ozone in the stratosphere, ground-level ozone is a harmful air pollutant." },
      { question: "What is a 'watershed'?", options: ["A building for storing water", "A critical moment in history", "An area of land that drains all its water into a common outlet like a river or lake", "A type of boat"], correctAnswer: "An area of land that drains all its water into a common outlet like a river or lake", fact: "Everything you do on the land within a watershed affects the quality of the water downstream." }
    ],
    8: [
      { question: "What is desalination?", options: ["Adding salt to water", "The process of removing salt from seawater to make it drinkable", "A type of sailing trip", "The study of deserts"], correctAnswer: "The process of removing salt from seawater to make it drinkable", fact: "Desalination is energy-intensive, which is a major drawback to its widespread use." },
      { question: "What is the primary material used to make paper?", options: ["Plastic", "Wood pulp", "Cotton", "Metal"], correctAnswer: "Wood pulp", fact: "Recycling paper uses less energy and water than making new paper from wood pulp." },
      { question: "What does it mean if a species is 'extinct'?", options: ["It is sleeping", "It is hiding", "There are no living individuals of that species left", "It is on vacation"], correctAnswer: "There are no living individuals of that species left", fact: "Scientists estimate that dozens of species go extinct every day." }
    ],
  },
  Hard: {
    1: [
      { question: "What is the 'Albedo Effect'?", options: ["The trapping of heat by greenhouse gases", "The reflection of solar radiation by a surface", "The process of water evaporating from plants", "The creation of acid rain"], correctAnswer: "The reflection of solar radiation by a surface", fact: "Melting sea ice is a feedback loop: as bright, reflective ice disappears, the dark ocean absorbs more heat, causing more ice to melt." },
      { question: "The Montreal Protocol is an international treaty designed to protect what?", options: ["The Amazon Rainforest", "Endangered Whales", "The Ozone Layer", "Antarctica"], correctAnswer: "The Ozone Layer", fact: "It's considered one of the most successful international environmental agreements in history, having phased out chemicals like CFCs." },
      { question: "What is eutrophication?", options: ["A type of deep-sea exploration", "The process of an ecosystem becoming enriched with nutrients", "A method for purifying water", "A geological formation"], correctAnswer: "The process of an ecosystem becoming enriched with nutrients", fact: "This can cause harmful algal blooms, leading to 'dead zones' in water bodies where oxygen levels are too low to support life." }
    ],
    2: [
      { question: "What is carbon sequestration?", options: ["A type of tax on pollution", "The process of capturing and storing atmospheric carbon dioxide", "The conversion of carbon into fuel", "A stock market for carbon"], correctAnswer: "The process of capturing and storing atmospheric carbon dioxide", fact: "Natural methods include reforestation, while technological methods involve capturing CO2 from power plants and storing it underground." },
      { question: "What does the term 'carrying capacity' mean in ecology?", options: ["The maximum weight an animal can carry", "The total amount of resources an ecosystem produces", "The maximum population size of a species that the environment can sustain indefinitely", "The speed at which a species can reproduce"], correctAnswer: "The maximum population size of a species that the environment can sustain indefinitely", fact: "Exceeding carrying capacity can lead to environmental degradation and a population crash." },
      { question: "The 'tragedy of the commons' describes a situation where...", options: ["A shared resource is depleted by individuals acting in their own self-interest", "A play has a very sad ending", "A community works together to preserve a resource", "A private resource is shared with the public"], correctAnswer: "A shared resource is depleted by individuals acting in their own self-interest", fact: "Examples include overfishing in international waters and overgrazing on public lands." }
    ],
    3: [
      { question: "What is biomagnification (or bioamplification)?", options: ["Using a microscope to see living things", "The increasing concentration of a substance in organisms at successive levels in a food chain", "The process of making organisms larger", "A form of renewable energy"], correctAnswer: "The increasing concentration of a substance in organisms at successive levels in a food chain", fact: "This is why toxins like mercury and DDT can be found in very high concentrations in top predators like eagles and tuna." },
      { question: "What is the primary goal of the Paris Agreement?", options: ["To ban all fossil fuels immediately", "To limit global warming to well below 2 degrees Celsius compared to pre-industrial levels", "To fund space exploration", "To create a single global currency"], correctAnswer: "To limit global warming to well below 2 degrees Celsius compared to pre-industrial levels", fact: "The agreement works on a 5-year cycle of increasingly ambitious climate action carried out by countries." },
      { question: "What are 'trophic levels' in an ecosystem?", options: ["Levels of pollution", "The position an organism occupies in a food chain", "Different types of soil layers", "Measures of water quality"], correctAnswer: "The position an organism occupies in a food chain", fact: "Level 1 is producers (plants), Level 2 is primary consumers (herbivores), Level 3 is secondary consumers (carnivores), and so on." }
    ],
    4: [
      { question: "What is ocean acidification?", options: ["A marketing term for sour candy", "The ongoing decrease in the pH of the Earth's oceans, caused by the uptake of CO2", "The process of cleaning up oil spills", "A natural cycle of the ocean's pH"], correctAnswer: "The ongoing decrease in the pH of the Earth's oceans, caused by the uptake of CO2", fact: "This makes it harder for marine organisms like corals, oysters, and clams to build their shells and skeletons." },
      { question: "A 'keystone species' is one that...", options: ["Is made of stone", "Is the most numerous in its ecosystem", "Has a disproportionately large effect on its environment relative to its abundance", "Is the main source of food for all other species"], correctAnswer: "Has a disproportionately large effect on its environment relative to its abundance", fact: "Sea otters are a classic example; they eat sea urchins, which would otherwise destroy kelp forests." },
      { question: "What is the difference between weather and climate?", options: ["They are the same thing", "Weather is long-term, climate is short-term", "Weather is what you get, climate is what you expect", "Climate is only about temperature"], correctAnswer: "Weather is what you get, climate is what you expect", fact: "Weather refers to short-term atmospheric conditions, while climate is the weather of a specific region averaged over a long period of time." }
    ],
    5: [
      { question: "What does 'environmental justice' advocate for?", options: ["Harsher penalties for littering", "The fair treatment and meaningful involvement of all people regardless of race or income, with respect to environmental laws", "Putting all factories in one designated area", "Giving animals the right to vote"], correctAnswer: "The fair treatment and meaningful involvement of all people regardless of race or income, with respect to environmental laws", fact: "Studies have shown that minority and low-income communities are often disproportionately exposed to pollution and environmental hazards." },
      { question: "What is a 'circular economy'?", options: ["An economy based on round objects", "An economic system aimed at eliminating waste and the continual use of resources", "An economy that does not grow", "An economy that only uses bartering"], correctAnswer: "An economic system aimed at eliminating waste and the continual use of resources", fact: "It contrasts with a traditional linear economy (make, use, dispose) by emphasizing repair, reuse, and recycling." },
      { question: "What are Volatile Organic Compounds (VOCs)?", options: ["Very stable chemicals", "Gases emitted from certain solids or liquids that have health effects", "Nutrients found in organic food", "A type of vitamin"], correctAnswer: "Gases emitted from certain solids or liquids that have health effects", fact: "VOCs are found in paints, cleaning supplies, pesticides, and building materials and can contribute to indoor air pollution." }
    ],
    6: [
      { question: "What is the primary cause of coral bleaching?", options: ["Fish eating the coral", "Darkness", "Unusually warm water temperatures", "Too much salt in the water"], correctAnswer: "Unusually warm water temperatures", fact: "When stressed by heat, corals expel the symbiotic algae living in their tissues, causing them to turn completely white." },
      { question: "What is 'fracking' (hydraulic fracturing)?", options: ["A type of dance", "A technique for extracting natural gas and oil from shale rock", "A method for filtering water", "A way to build earthquake-proof buildings"], correctAnswer: "A technique for extracting natural gas and oil from shale rock", fact: "Fracking is controversial due to concerns about water contamination, air pollution, and induced seismic activity." },
      { question: "What is the significance of the 'Anthropocene' epoch?", options: ["It refers to the age of dinosaurs", "It is a proposed geological epoch dating from the commencement of significant human impact on Earth's geology and ecosystems", "It is the period before humans existed", "It is a geological epoch on Mars"], correctAnswer: "It is a proposed geological epoch dating from the commencement of significant human impact on Earth's geology and ecosystems", fact: "There is debate about its starting point, with some suggesting the Industrial Revolution and others the nuclear age." }
    ],
    7: [
      { question: "What are 'ecosystem services'?", options: ["Jobs related to the environment", "The many and varied benefits to humans provided by the natural environment", "A delivery service for organic food", "A government environmental agency"], correctAnswer: "The many and varied benefits to humans provided by the natural environment", fact: "Examples include pollination of crops by bees, water filtration by wetlands, and climate regulation by forests." },
      { question: "What does the IUCN Red List categorize?", options: ["The world's best national parks", "The global conservation status of biological species", "The most polluted cities", "The most profitable green companies"], correctAnswer: "The global conservation status of biological species", fact: "It is the world's most comprehensive inventory of the global conservation status of plant and animal species." },
      { question: "What is 'permaculture'?", options: ["A permanent culture of a single crop", "An approach to land management that adopts arrangements observed in flourishing natural ecosystems", "A type of hair treatment", "A government that never changes"], correctAnswer: "An approach to land management that adopts arrangements observed in flourishing natural ecosystems", fact: "It is a design philosophy that follows a set of ethics: care for the Earth, care for people, and fair share." }
    ],
// FIX: Completed the question object for Hard difficulty, stage 8, and added two more questions.
    8: [
      {
        question: "What is the 'Precautionary Principle' in environmental policy?",
        options: [
            "Acting only after harm is proven",
            "When an activity raises threats of harm to the environment or human health, precautionary measures should be taken even if some cause-and-effect relationships are not fully established scientifically.",
            "That all new technologies should be considered safe until proven harmful.",
            "A principle for prioritizing economic development over environmental protection."
        ],
        correctAnswer: "When an activity raises threats of harm to the environment or human health, precautionary measures should be taken even if some cause-and-effect relationships are not fully established scientifically.",
        fact: "It essentially means 'better safe than sorry' and is a core principle in EU environmental law."
      },
       {
        question: "What is 'thermal runaway' in the context of climate change?",
        options: ["A cooling effect from cloud cover", "A positive feedback loop where a warming climate causes changes that lead to even more warming", "The process of heat escaping into space", "A type of renewable energy from volcanoes"],
        correctAnswer: "A positive feedback loop where a warming climate causes changes that lead to even more warming",
        fact: "An example is the melting of Arctic permafrost, which releases methane, a potent greenhouse gas, leading to further warming."
      },
      {
        question: "What does 'downcycling' mean in the context of recycling?",
        options: ["Recycling something into a product of the same quality", "A type of exercise on a bicycle", "The process of converting waste materials into new materials of lesser quality and reduced functionality", "A method for increasing the value of recycled goods"],
        correctAnswer: "The process of converting waste materials into new materials of lesser quality and reduced functionality",
        fact: "For example, recycling plastic bottles into fiber for carpets is downcycling, as the fiber cannot be recycled back into bottles."
      }
    ],
  },
};

// FIX: Added LEADERBOARD_DATA to be exported and used in Leaderboard.tsx.
export const LEADERBOARD_DATA: LeaderboardPlayer[] = [
  { rank: 1, name: 'EcoWarrior', score: 9850 },
  { rank: 2, name: 'GreenThumb', score: 9500 },
  { rank: 3, name: 'PlanetProtector', score: 9120 },
  { rank: 4, name: 'AquaFriend', score: 8800 },
  { rank: 5, name: 'SolarFlare', score: 8540 },
];

// FIX: Added BADGES to be exported and used in ProfileScreen.tsx.
export const BADGES = [
  { id: 1, name: 'Recycling Rookie', description: 'Completed Stage 1 and learned the basics of recycling.' },
  { id: 2, name: 'Water Wizard', description: 'Completed Stage 2 by mastering water conservation facts.' },
  { id: 3, name: 'Conservation Champ', description: 'Completed Stage 3 and proved your knowledge on protecting species.' },
  { id: 4, name: 'Oceanic Overseer', description: 'Completed Stage 4, defending our largest bodies of water.' },
  { id: 5, name: 'Reduce Ranger', description: 'Completed Stage 5 with expertise in the most important "R".' },
  { id: 6, name: 'Material Master', description: 'Completed Stage 6, showing you know your aluminum from your steel.' },
  { id: 7, name: 'Ecosystem Expert', description: 'Completed Stage 7 by understanding the delicate balance of nature.' },
  { id: 8, name: 'Planet Pro', description: 'Completed Stage 8, demonstrating advanced environmental knowledge.' },
];
